# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/runnymede/unzip-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries

PRODUCT_COPY_FILES += \
    vendor/htc/runnymede/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so

# Audio Blobs
PRODUCT_COPY_FILES += \
    vendor/htc/runnymede/proprietary/lib/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/htc/runnymede/proprietary/lib/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/runnymede/proprietary/etc/AdieHWCodec.csv:system/etc/AdieHWCodec.csv \
    vendor/htc/runnymede/proprietary/etc/AudioBTID.csv:system/etc/AudioBTID.csv \
    vendor/htc/runnymede/proprietary/etc/audio_effects.conf:system/etc/audio_effects.conf \
    vendor/htc/runnymede/proprietary/etc/CodecDSPID.txt:system/etc/CodecDSPID.txt \
    vendor/htc/runnymede/proprietary/etc/IOTable.txt:system/etc/IOTable.txt \
    vendor/htc/runnymede/proprietary/etc/TPA2051_CFG.csv:system/etc/TPA2051_CFG.csv \
    vendor/htc/runnymede/proprietary/etc/TPA2051_CFG_BEATS_HW.csv:system/etc/TPA2051_CFG_BEATS_HW.csv \
    vendor/htc/runnymede/proprietary/etc/firmware/default.acdb:system/etc/firmware/default.acdb \
    vendor/htc/runnymede/proprietary/etc/firmware/default_org.acdb:system/etc/firmware/default_org.acdb \
    vendor/htc/runnymede/proprietary/etc/firmware/default_mfg.acdb:system/etc/firmware/default_mfg.acdb \
    vendor/htc/runnymede/proprietary/etc/firmware/default_org_wb.acdb:system/etc/firmware/default_org_wb.acdb \

# Wifi/BT firmware
PRODUCT_COPY_FILES += \
    vendor/htc/runnymede/proprietary/etc/firmware/BCM4330B1_002.001.003.0550.0568.hcd:system/etc/firmware/BCM4330B1_002.001.003.0550.0568.hcd \
    vendor/htc/runnymede/proprietary/etc/firmware/fw_bcm4330_apsta_b1.bin:system/etc/firmware/fw_bcm4330_apsta_b1.bin \
    vendor/htc/runnymede/proprietary/etc/firmware/fw_bcm4330_apsta_b2.bin:system/etc/firmware/fw_bcm4330_apsta_b2.bin \
    vendor/htc/runnymede/proprietary/etc/firmware/fw_bcm4330_b2.bin:system/etc/firmware/fw_bcm4330_b2.bin \
    vendor/htc/runnymede/proprietary/etc/firmware/fw_bcm4330_b1.bin:system/etc/firmware/fw_bcm4330_b1.bin \
    vendor/htc/runnymede/proprietary/etc/firmware/fw_bcm4330_p2p_b2.bin:system/etc/firmware/fw_bcm4330_p2p_b2.bin \
    vendor/htc/runnymede/proprietary/etc/firmware/fw_bcm4330_p2p_b1.bin:system/etc/firmware/fw_bcm4330_p2p_b1.bin \
    vendor/htc/runnymede/proprietary/etc/calibration:system/etc/calibration

# HW files
#vendor/htc/runnymede/proprietary/lib/hw/hwcomposer.msm7x30.so:system/lib/hw/hwcomposer.msm7x30.so \
#vendor/htc/runnymede/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
#vendor/htc/runnymede/proprietary/lib/hw/gps.runnymede.so:system/lib/hw/gps.runnymede.so \
#vendor/htc/runnymede/proprietary/lib/hw/sensors.runnymede.so:system/lib/hw/sensors.runnymede.so
PRODUCT_COPY_FILES += \
    vendor/htc/runnymede/proprietary/lib/hw/camera.default.so:system/lib/hw/camera.default.so \
    vendor/htc/runnymede/proprietary/lib/hw/copybit.msm7x30.so:system/lib/hw/copybit.msm7x30.so \
    vendor/htc/runnymede/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
    vendor/htc/runnymede/proprietary/lib/hw/audio.primary.msm7x30.so:system/lib/hw/audio.primary.msm7x30.so \
    vendor/htc/runnymede/proprietary/lib/hw/lights.msm7x30.so:system/lib/hw/lights.msm7x30.so 

# EGL
PRODUCT_COPY_FILES += \
    vendor/htc/runnymede/proprietary/lib/egl/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \
    vendor/htc/runnymede/proprietary/lib/egl/libGLES_android.so:/system/lib/egl/libGLES_android.so \
    vendor/htc/runnymede/proprietary/lib/egl/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/htc/runnymede/proprietary/lib/egl/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/runnymede/proprietary/lib/egl/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/runnymede/proprietary/lib/egl/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/runnymede/proprietary/lib/libOpenVG.so:/system/lib/libOpenVG.so \
    vendor/htc/runnymede/proprietary/lib/libC2D2.so:/system/lib/libC2D2.so \
    vendor/htc/runnymede/proprietary/lib/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/runnymede/proprietary/lib/libsc-a2xx.so:/system/lib/libsc-a2xx.so

#	From Primou, not existing in Runnymede
#    vendor/htc/runnymede/proprietary/lib/libcentralZoomTransition.so:system/lib/libcentralZoomTransition.so \
#    vendor/htc/runnymede/proprietary/lib/libchromatix_s5k4e5yx_hdr.so:system/lib/libchromatix_s5k4e5yx_hdr.so \
#    vendor/htc/runnymede/proprietary/lib/libchromatix_s5k4e5yx_hfr_4x.so:system/lib/libchromatix_s5k4e5yx_hfr_4x.so \
#    vendor/htc/runnymede/proprietary/lib/libcubicRotateTransition.so:system/lib/libcubicRotateTransition.so \
#    vendor/htc/runnymede/proprietary/lib/libzoomTransition.so:system/lib/libzoomTransition.so \
#    vendor/htc/runnymede/proprietary/lib/libmmcamera_rawchipproc.so:system/lib/libmmcamera_rawchipproc.so \
#    vendor/htc/runnymede/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
#    vendor/htc/runnymede/proprietary/lib/libmmparser.so:system/lib/3libmmparser.so \
#    vendor/htc/runnymede/proprietary/lib/libmmparser_divxdrmlib.so:system/lib/libmmparser_divxdrmlib.so \
#    vendor/htc/runnymede/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
#    vendor/htc/runnymede/proprietary/lib/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
#    vendor/htc/runnymede/proprietary/lib/libqmi.so:/system/lib/libqmi.so \
#    vendor/htc/runnymede/proprietary/lib/libdll.so:/system/lib/libdll.so \
#    vendor/htc/runnymede/proprietary/lib/libdiag.so:/system/lib/libdiag.so \
#    vendor/htc/runnymede/proprietary/lib/libidl.so:/system/lib/libidl.so \
#    vendor/htc/runnymede/proprietary/lib/libnetmgr.so:/system/lib/libnetmgr.so \
#    vendor/htc/runnymede/proprietary/lib/libdsutils.so:/system/lib/libdsutils.so \
#    vendor/htc/runnymede/proprietary/lib/libqdp.so:/system/lib/libqdp.so \
#    vendor/htc/runnymede/proprietary/bin/bma150_usr:/system/bin/bma150_usr \
#    vendor/htc/runnymede/proprietary/lib/libOlaEngine.so:system/lib/libOlaEngine.so \

# Camera
PRODUCT_COPY_FILES += \
    vendor/htc/runnymede/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/htc/runnymede/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
    vendor/htc/runnymede/proprietary/bin/awb_camera:/system/bin/awb_camera \
    vendor/htc/runnymede/proprietary/lib/libcameraface.so:system/lib/libcameraface.so \
    vendor/htc/runnymede/proprietary/lib/libcamerapp.so:system/lib/libcamerapp.so \
    vendor/htc/runnymede/proprietary/lib/libchromatix_s5k4e5yx_default_video.so:system/lib/libchromatix_s5k4e5yx_default_video.so \
    vendor/htc/runnymede/proprietary/lib/libchromatix_s5k4e5yx_hfr.so:system/lib/libchromatix_s5k4e5yx_hfr.so \
    vendor/htc/runnymede/proprietary/lib/libchromatix_s5k4e5yx_preview.so:system/lib/libchromatix_s5k4e5yx_preview.so \
    vendor/htc/runnymede/proprietary/lib/libmmipl.so:/system/lib/libmmipl.so \
    vendor/htc/runnymede/proprietary/lib/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/htc/runnymede/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/htc/runnymede/proprietary/bin/lsc_camera:/system/bin/lsc_camera \
    vendor/htc/runnymede/proprietary/lib/liboemcamera.so:/system/lib/liboemcamera.so

# Ril
PRODUCT_COPY_FILES += \
    vendor/htc/runnymede/proprietary/lib/libhtc_ril.so:/system/lib/libhtc_ril.so

# Random Crap..Verify necessity
#    vendor/htc/runnymede/proprietary/bin/zcb:/system/bin/zcb \ 
PRODUCT_COPY_FILES += \
    vendor/htc/runnymede/proprietary/lib/libmm-color-convertor.so:/system/lib/libmm-color-convertor.so \
    vendor/htc/runnymede/proprietary/lib/libmmosal.so:/system/lib/libmmosal.so \
    vendor/htc/runnymede/proprietary/lib/libmmparser.so:/system/lib/libmmparser.so \
    vendor/htc/runnymede/proprietary/lib/libmmparser_lite.so:/system/lib/libmmparser_lite.so \
    vendor/htc/runnymede/proprietary/bin/logcat2:/system/bin/logcat2 \
    vendor/htc/runnymede/proprietary/bin/htc_ebdlogd:/system/bin/htc_ebdlogd \
    vendor/htc/runnymede/proprietary/bin/rmt_storage:/system/bin/rmt_storage \
    vendor/htc/runnymede/proprietary/lib/libgemini.so:/system/lib/libgemini.so \
    vendor/htc/runnymede/proprietary/lib/libposteffect.so:/system/lib/libposteffect.so \
    vendor/htc/runnymede/proprietary/lib/libv8.so:/system/lib/libv8.so \
    vendor/htc/runnymede/proprietary/lib/libhardware_legacy.so:/system/lib/libhardware_legacy.so

